### ISSUE TITLE
navy topography files are not provided with the standard download

### ISSUE THREAD

**Issue by edwinpgerber** [mjucker/MiMA#24]
I noticed that input.nml asks for the "navy" topography and water files, but only "lmask.T42.nc" is provided in the input/INPUT directory.  This is probably something we should fix before releasing MiMA 2.0.

&topography_nml
        topog_file = 'INPUT/navy_topography.data.nc',
        water_file = 'INPUT/navy_pctwater.data.nc' /

**Comment by rosscastle** [comment]
Hello,

I myself have searched for these files for use with Isca (Geoff Vallis's group), but could not find them anywhere and so had to create my own high res-file (nearly 1/6th degree, which I would be happy to provide, and soon will create a 1/8th degree). 

I needed the navy_topography.data.nc in order to generate subgrid orography variance for the orographic GWD scheme. To my knowledge it is not used for anything else. I don't know about the water data.

If you do find the original files I'd love to have a copy. They contain grid box edge values in radians not degrees.

Thanks,

Ross

**Comment by mjucker** [comment]
These files are available from GFDL, and will be added for the release of v2.0. Hang on tight! BTW, they are used for topography as well as the GWD scheme, and the water data is used for the land-sea mask. Of course, this being MiMA, all of this is optional and just a namelist variable away.

**Comment by mjucker** [comment]
files added with commit f5e4813
